import { getOctokit, parseGitHubUrl } from './client'

export interface AutoCreatePRInput {
  repoUrl: string
  branchName: string
  taskPrompt: string
  agentName: string
  baseBranch?: string
}

export interface PRInfo {
  prNumber: number
  prUrl: string
  title: string
  body: string
}

/**
 * Generate a descriptive PR Title and Body based on task details and agent execution context
 */
export function generatePRMetadata(taskPrompt: string, agentName: string, branchName: string) {
  const sanitizedPrompt = taskPrompt.trim()
  const firstLine = sanitizedPrompt.split('\n')[0]
  const title = firstLine.length > 70 ? `${firstLine.substring(0, 67)}...` : firstLine

  const body = `## 🤖 GUIDESOFT.ONLINE Execution Summary

**Task Description:**
> ${sanitizedPrompt}

---
- **Agent Executed:** \`${agentName}\`
- **Branch:** \`${branchName}\`
- **Generated By:** Vercel Sandbox GUIDESOFT.ONLINE

### 🚀 Key Highlights & Changes
- Implemented task requirements automatically inside isolated Vercel Sandbox.
- Changes committed and pushed to branch \`${branchName}\`.

---
*Created automatically by [GUIDESOFT.ONLINE](https://www.guidesoft.online).*
`

  return { title, body }
}

/**
 * Creates a GitHub PR with automatically generated metadata
 */
export async function autoCreatePullRequest(input: AutoCreatePRInput): Promise<{
  success: boolean
  pr?: PRInfo
  error?: string
}> {
  const { repoUrl, branchName, taskPrompt, agentName, baseBranch = 'main' } = input

  try {
    const octokit = await getOctokit()

    if (!octokit.auth) {
      return { success: false, error: 'GitHub account not connected. Please connect your GitHub account in settings.' }
    }

    const parsed = parseGitHubUrl(repoUrl)
    if (!parsed) {
      return { success: false, error: 'Invalid GitHub repository URL' }
    }

    const { owner, repo } = parsed
    const { title, body } = generatePRMetadata(taskPrompt, agentName, branchName)

    const response = await octokit.rest.pulls.create({
      owner,
      repo,
      title,
      body,
      head: branchName,
      base: baseBranch,
    })

    return {
      success: true,
      pr: {
        prNumber: response.data.number,
        prUrl: response.data.html_url,
        title,
        body,
      },
    }
  } catch (error: unknown) {
    console.error('Error auto-creating PR:', error)
    if (error && typeof error === 'object' && 'status' in error) {
      const status = (error as { status: number }).status
      if (status === 422) {
        return { success: false, error: 'A Pull Request already exists for this branch or branch was not found.' }
      }
      if (status === 403 || status === 404) {
        return { success: false, error: 'Permission denied or repository not accessible with current GitHub token.' }
      }
    }
    return { success: false, error: 'Failed to create pull request.' }
  }
}
