'use client'

import { useState } from 'react'
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Bot, Layers, ArrowRight, Play, CheckCircle2, Sparkles, Code2, ShieldAlert, Cpu } from 'lucide-react'

interface WorkflowStep {
  id: string
  role: 'planner' | 'coder' | 'reviewer'
  agent: string
  prompt: string
  status: 'idle' | 'running' | 'completed'
}

export default function WorkflowPage() {
  const [repoUrl, setRepoUrl] = useState('')
  const [steps, setSteps] = useState<WorkflowStep[]>([
    {
      id: '1',
      role: 'planner',
      agent: 'claude-code',
      prompt: 'Analyze repository structure and outline architectural modifications for new feature.',
      status: 'idle',
    },
    {
      id: '2',
      role: 'coder',
      agent: 'cursor-cli',
      prompt: 'Implement feature requirements according to the plan generated by the planning agent.',
      status: 'idle',
    },
    {
      id: '3',
      role: 'reviewer',
      agent: 'gemini-cli',
      prompt: 'Run tests, verify linting, and generate pull request notes.',
      status: 'idle',
    },
  ])

  const [isExecuting, setIsExecuting] = useState(false)
  const [currentStepIndex, setCurrentStepIndex] = useState<number | null>(null)

  const availableAgents = [
    { id: 'claude-code', name: 'Claude Code', provider: 'Anthropic' },
    { id: 'codex-cli', name: 'OpenAI Codex CLI', provider: 'OpenAI' },
    { id: 'copilot-cli', name: 'GitHub Copilot CLI', provider: 'GitHub' },
    { id: 'cursor-cli', name: 'Cursor CLI', provider: 'Cursor' },
    { id: 'gemini-cli', name: 'Google Gemini CLI', provider: 'Google' },
    { id: 'opencode', name: 'OpenCode', provider: 'Open Source' },
  ]

  const handleAddStep = () => {
    const newStep: WorkflowStep = {
      id: Date.now().toString(),
      role: 'coder',
      agent: 'copilot-cli',
      prompt: 'Perform subsequent refinement or refactoring.',
      status: 'idle',
    }
    setSteps([...steps, newStep])
  }

  const handleUpdateStep = (id: string, field: keyof WorkflowStep, value: string) => {
    setSteps(steps.map((s) => (s.id === id ? { ...s, [field]: value } : s)))
  }

  const handleRemoveStep = (id: string) => {
    if (steps.length <= 1) return
    setSteps(steps.filter((s) => s.id !== id))
  }

  const handleRunWorkflow = async () => {
    if (!repoUrl.trim()) {
      alert('Please enter a GitHub repository URL')
      return
    }

    setIsExecuting(true)
    for (let i = 0; i < steps.length; i++) {
      setCurrentStepIndex(i)
      setSteps((prev) => prev.map((st, idx) => (idx === i ? { ...st, status: 'running' } : st)))

      // Simulate step progress / API trigger
      await new Promise((resolve) => setTimeout(resolve, 2000))

      setSteps((prev) => prev.map((st, idx) => (idx === i ? { ...st, status: 'completed' } : st)))
    }
    setIsExecuting(false)
    setCurrentStepIndex(null)
  }

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 p-6 md:p-12 space-y-8 font-sans">
      {/* Header */}
      <div className="max-w-5xl mx-auto space-y-2">
        <div className="flex items-center gap-2 text-emerald-400 font-bold text-sm tracking-wide uppercase">
          <Layers className="w-4 h-4" />
          <span>Multi-Agent Workflow Orchestrator</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight">Sequential AI Agent Pipelines</h1>
        <p className="text-zinc-400 text-sm max-w-2xl">
          Chain specialized AI agents together inside an isolated Vercel Sandbox. Delegate planning to Claude, coding to
          Cursor, and test verification to Gemini seamlessly.
        </p>
      </div>

      {/* Target Repo Setup */}
      <div className="max-w-5xl mx-auto">
        <Card className="bg-zinc-900 border-zinc-800 text-zinc-100">
          <CardHeader>
            <CardTitle className="text-base font-semibold flex items-center gap-2">
              <Code2 className="w-4 h-4 text-emerald-400" /> Target Repository
            </CardTitle>
            <CardDescription className="text-zinc-400 text-xs">
              Provide the GitHub repository URL where agents will perform changes.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <input
              type="url"
              placeholder="https://github.com/owner/repository"
              value={repoUrl}
              onChange={(e) => setRepoUrl(e.target.value)}
              className="w-full bg-zinc-950 border border-zinc-800 rounded-md px-4 py-2 text-sm text-zinc-100 outline-none focus:border-emerald-500 font-mono"
            />
          </CardContent>
        </Card>
      </div>

      {/* Pipeline Steps Visualizer */}
      <div className="max-w-5xl mx-auto space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <Cpu className="w-5 h-5 text-emerald-400" /> Pipeline Steps ({steps.length})
          </h2>
          <Button
            variant="outline"
            size="sm"
            onClick={handleAddStep}
            disabled={isExecuting}
            className="border-zinc-800 bg-zinc-900 text-zinc-200 hover:bg-zinc-800 text-xs"
          >
            + Add Agent Step
          </Button>
        </div>

        <div className="space-y-4">
          {steps.map((step, index) => (
            <Card
              key={step.id}
              className={`bg-zinc-900 border transition-all ${
                step.status === 'running'
                  ? 'border-emerald-500 shadow-lg shadow-emerald-950/40'
                  : step.status === 'completed'
                    ? 'border-emerald-800/60'
                    : 'border-zinc-800'
              }`}
            >
              <CardContent className="p-4 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="bg-zinc-800 text-zinc-300 font-mono text-[11px]">
                      Step {index + 1}
                    </Badge>
                    <span className="text-sm font-semibold capitalize text-emerald-300">{step.role} Agent</span>
                  </div>

                  <div className="flex items-center gap-2">
                    {step.status === 'completed' && (
                      <span className="text-emerald-400 text-xs flex items-center gap-1 font-medium">
                        <CheckCircle2 className="w-3.5 h-3.5" /> Done
                      </span>
                    )}
                    {step.status === 'running' && (
                      <span className="text-amber-400 text-xs flex items-center gap-1 animate-pulse font-medium">
                        <Sparkles className="w-3.5 h-3.5" /> Executing in Sandbox...
                      </span>
                    )}
                    {steps.length > 1 && (
                      <button
                        onClick={() => handleRemoveStep(step.id)}
                        disabled={isExecuting}
                        className="text-zinc-500 hover:text-red-400 text-xs px-2 py-0.5 rounded"
                      >
                        Remove
                      </button>
                    )}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  <div className="space-y-1">
                    <label className="text-[11px] text-zinc-400 font-medium">Agent Engine</label>
                    <select
                      value={step.agent}
                      onChange={(e) => handleUpdateStep(step.id, 'agent', e.target.value)}
                      disabled={isExecuting}
                      className="w-full bg-zinc-950 border border-zinc-800 rounded px-3 py-1.5 text-xs text-zinc-200 outline-none focus:border-emerald-500"
                    >
                      {availableAgents.map((ag) => (
                        <option key={ag.id} value={ag.id}>
                          {ag.name} ({ag.provider})
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="space-y-1 md:col-span-2">
                    <label className="text-[11px] text-zinc-400 font-medium">Step Instructions & Prompt</label>
                    <input
                      type="text"
                      value={step.prompt}
                      onChange={(e) => handleUpdateStep(step.id, 'prompt', e.target.value)}
                      disabled={isExecuting}
                      className="w-full bg-zinc-950 border border-zinc-800 rounded px-3 py-1.5 text-xs text-zinc-200 outline-none focus:border-emerald-500"
                    />
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Execution Trigger */}
        <div className="pt-4 flex justify-end">
          <Button
            onClick={handleRunWorkflow}
            disabled={isExecuting || !repoUrl.trim()}
            className="bg-emerald-600 hover:bg-emerald-500 text-white font-semibold px-6 py-2 gap-2 shadow-lg shadow-emerald-950/60"
          >
            <Play className="w-4 h-4 fill-current" />
            {isExecuting ? `Executing Step ${(currentStepIndex ?? 0) + 1}...` : 'Run Pipeline Workflow'}
          </Button>
        </div>
      </div>
    </div>
  )
}
